name = "sageblog-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
SITE_URL    = "https://sageblog.cfd"
API_URL     = "https://api.sageblog.cfd"

[triggers]
crons = ["*/10 * * * *"]

[[d1_databases]]
binding       = "DB"
database_name = "sageblog-db"
database_id   = "d14f71cb-83e6-41cd-8038-0a6afea736ad"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV_STORE"
id      = "ecea8cf5e8e04313b738497c18f6927f"

[[r2_buckets]]
binding     = "IMAGES"
bucket_name = "sageblog-images"

[[routes]]
pattern = "api.sageblog.cfd"
custom_domain = true

[[routes]]
pattern = "sageblog.cfd/*"
zone_name = "sageblog.cfd"

# Secrets (set via wrangler secret put):
#   JWT_SECRET
#   ADMIN_SECRET
